Extend the functionality of hover in rbs files.
soutaro/steep pull request #397
Opened 2021-07-09 11:23 UTC by Yuuki77

add hover supports for `RBS::Types::ClassInstance`, `RBS::Types::ClassSingleton` and `RBS::Types::Interface`.

When these are hovered, the information and comments will now be displayed!

![image](https://user-images.githubusercontent.com/18569016/125070604-28232a00-e0f3-11eb-85eb-88bb01082d4d.png)

### How to test
crate a rbs file with this content and you can confirm that you can see the information when you hover them
```rbs
# my comment
class Foo [T] < Parent[T]
end

class Parent [in T]
end

module Hoge
end

class Qux
  @foo: Foo[Hoge]
end

interface _Fooable
  def foo: () -> nil
end

class C
  def foo: (_Fooable) -> singleton(String)
end
```

2021-07-12 10:11 UTC, soutaro requested changes
The rest of the code looks good.

2021-07-12 10:11 UTC, soutaro commented on lib/steep/services/hover_content.rb
> +              location: location,
Use `location[:name]` here to highlight only name of the interface.

2021-07-12 13:43 UTC, Yuuki77 commented
@soutaro Thank you for the reviews!
I have updated it https://github.com/soutaro/steep/pull/397/commits/1545d6b6b34a85bde47f2c253673c359dacec421

2021-07-20 14:04 UTC, soutaro approved these changes
💪

2021-07-20 14:04 UTC, merged